### PR TITLE
Harden autolools machinery

### PR DESCRIPTION
**Pull request by jgmbenoit**
Description: upstream source: autotilization: hardenning
 Attempt to harden the upstream autotools scripts.
Origin: vendor, Debian
Author: Jerome Benoit <calculus@rezozer.net>
Last-Update: 2018-06-08

### CODE REVIEW

**Comment by slayoo** [comment]
thank you!

**Comment by slayoo** [comment]
Could you please explain the rationale behind introducing the check target in the Makefile? Thanks!

**Comment by jgmbenoit** [comment]
The former check mechanism is rather replaced by the native AutoMake one: sticking to AM leads to write simple Makefile.am, easier to maintain on the long run. In short, the rational is simply to get a better integration within the AutoTools chain, and thus within the packaging machinery used by major Linux/GNU distribution (e.g., Debian).
In short, this will simplify the life of major distribution maintainers.

**Comment by slayoo** [comment]
Thanks!

**Pull request merged**
